server:
  port: 8085
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
    reactor.netty: TRACE
spring:
  redis:
    host: ${redis-host:127.0.0.1}
    port: ${redis-port:6379}
    password: 123456
    timeout: 1000
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**

hope:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: lzsdash
    # 设置jwt过期时间
    ttl: 323423000
    # 设置前端传递过来的令牌名称
    token-name: token