server:
  port: 8085
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
    reactor.netty: TRACE
spring:
  redis:
    host: ${redis-host:127.0.0.1}
    port: ${redis-port:6379}
    timeout: 1000
    password: 123456
    database: 1
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: user-documents-service
          uri: lb://user-service
          predicates:
            - Path=/documents/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**
        - id: folder-service
          uri: lb://document-service
          predicates:
            - Path=/folder/**
        - id: ai-service
          uri: lb://user-service
          predicates:
            - Path=/ai/**
        - id: share-service
          uri: lb://document-service
          predicates:
            - Path=/share/**
        - id: search-service
          uri: lb://document-service
          predicates:
            - Path=/search/**
        - id: order-service
          uri: lb://user-service
          predicates:
            - Path=/order/**
        - id: user-element-service
          uri: lb://user-service
          predicates:
            - Path=/element/**

dubbo:
  consumer:
    timeout: 30000
    retries: 0
  application:
    qos-enable: false
    qos-accept-foreign-ip: false
    name: geteway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: geteway-nacos-registry
    address: nacos://localhost:8848
    parameters:
      # 修改
      namespace: cd5b4c92-4168-411c-afb5-fea7b468821e
      # 修改
      group: dubbo

hope:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: lzsdash
    # 设置jwt过期时间
    ttl: 323423000
    # 设置前端传递过来的令牌名称
    token-name: token
